"""Чек-лист правил для code-review.

Каждое правило — dict:
    id          уникальный идентификатор (например, "CORR-001")
    category    correctness | security | performance | style | tests | edge_cases
    severity    critical | warning | nit
    pattern     регулярное выражение (re.search, применяется к каждой добавленной строке diff)
    message     описание проблемы (выводится в отчёте)
    suggestion  предлагаемое исправление

Правила — эвристики: возможны ложные срабатывания, каждую находку
нужно проверять вручную перед публикацией ревью.
"""

RULES = [
    # ---------------------------------------------------------------- correctness
    {
        "id": "CORR-001",
        "category": "correctness",
        "severity": "warning",
        "pattern": r"(?i)\b(null|none|nil|undefined)\s*==\s*\w+",
        "message": "Сравнение с null/None в Yoda-форме: легко перепутать с присваиванием.",
        "suggestion": "Пишите значение слева, константу справа: `x is None` / `x == null`.",
    },
    {
        "id": "CORR-002",
        "category": "correctness",
        "severity": "warning",
        "pattern": r"\d+\.\d+\s*==\s*\w+|\w+\s*==\s*\d+\.\d+",
        "message": "Сравнение чисел с плавающей точкой через `==` ненадёжно (IEEE-754).",
        "suggestion": "Сравнивайте с допуском: `abs(a - b) < 1e-9` или используйте Decimal.",
    },
    {
        "id": "CORR-003",
        "category": "correctness",
        "severity": "warning",
        "pattern": r"^\s*except\s*:",
        "message": "Голый `except:` ловит все исключения, включая KeyboardInterrupt и SystemExit.",
        "suggestion": "Укажите конкретный тип: `except ValueError:` и обработайте его явно.",
    },
    {
        "id": "CORR-004",
        "category": "correctness",
        "severity": "warning",
        "pattern": r"^\s*except\s+[^:]+:\s*pass\s*$",
        "message": "Исключение молча проглатывается (`except ...: pass`).",
        "suggestion": "Логируйте ошибку или пробрасывайте её дальше (`raise`).",
    },
    {
        "id": "CORR-005",
        "category": "correctness",
        "severity": "nit",
        "pattern": r"(?i)\b(TODO|FIXME|HACK|XXX)\b",
        "message": "Оставлен маркер незавершённой работы.",
        "suggestion": "Заведите задачу в трекере и уберите маркер перед мержем.",
    },
    {
        "id": "CORR-006",
        "category": "correctness",
        "severity": "nit",
        "pattern": r"(?i)\bconsole\.(log|debug|warn)\b",
        "message": "Отладочный вывод в консоль остался в коде.",
        "suggestion": "Удалите console.log или замените на штатный логгер.",
    },
    {
        "id": "CORR-007",
        "category": "correctness",
        "severity": "warning",
        "pattern": r"\blen\s*\([^)]*\)\s*(==|!=|<=|>=|<|>)\s*0",
        "message": "Проверка пустоты через len() избыточна и медленнее.",
        "suggestion": "Используйте `if not x:` / `if x:` — идиоматично и быстрее.",
    },
    {
        "id": "CORR-008",
        "category": "correctness",
        "severity": "warning",
        "pattern": r"\b==\s*[\"']\s*[\"']",
        "message": "Сравнение с пустой строкой через `== \"\"`.",
        "suggestion": "Используйте `if not s:` — покрывает и None, и пустую строку.",
    },
    {
        "id": "CORR-009",
        "category": "correctness",
        "severity": "warning",
        "pattern": r"\bthreading\.(Thread|Lock|RLock)\b",
        "message": "Используется многопоточность: проверьте, что все обращения к общему состоянию защищены блокировкой (гонка данных).",
        "suggestion": "Оберните чтение/запись общего состояния в `with lock:` или используйте потокобезопасные структуры.",
    },
    {
        "id": "CORR-010",
        "category": "correctness",
        "severity": "warning",
        "pattern": r"fetchone\(\)\s*\[",
        "message": "fetchone() может вернуть None — обращение `[0]` упадёт с TypeError.",
        "suggestion": "Проверяйте результат: `row = cur.fetchone(); if row is None: return None`.",
    },
    {
        "id": "CORR-011",
        "category": "correctness",
        "severity": "warning",
        "pattern": r"def\s+\w+\([^)]*=\s*(\[\]|\{\})",
        "message": "Изменяемый объект как значение аргумента по умолчанию — общий для всех вызовов.",
        "suggestion": "Используйте `def f(x=None): x = x or []`.",
    },
    # ---------------------------------------------------------------- security
    {
        "id": "SEC-001",
        "category": "security",
        "severity": "critical",
        "pattern": r"(?i)(?=.*\b(select|insert|update|delete)\b)(?=.*(f[\"']|[\"']\s*\+))",
        "message": "SQL-запрос собирается из f-строки или конкатенации — риск SQL-инъекции.",
        "suggestion": "Используйте параметризованные запросы: `cursor.execute(sql, (param,))`.",
    },
    {
        "id": "SEC-002",
        "category": "security",
        "severity": "critical",
        "pattern": r"\b(eval|exec)\s*\(",
        "message": "eval/exec выполняют произвольный код — RCE при недоверенном вводе.",
        "suggestion": "Замените на безопасный парсер: ast.literal_eval, json.loads и т.п.",
    },
    {
        "id": "SEC-003",
        "category": "security",
        "severity": "critical",
        "pattern": r"\b(os\.system|subprocess\.(run|Popen|call|check_output))\s*\([^)]*shell\s*=\s*True",
        "message": "shell=True с конкатенацией команд — риск command injection.",
        "suggestion": "Передавайте аргументы списком без shell=True.",
    },
    {
        "id": "SEC-004",
        "category": "security",
        "severity": "critical",
        "pattern": r"(?i)\b(password|passwd|api[_-]?key|secret|token)\s*[:=]\s*[\"'][^\"']+[\"']",
        "message": "Секрет захардкожен в коде — попадёт в историю git.",
        "suggestion": "Вынесите в переменные окружения или секрет-менеджер.",
    },
    {
        "id": "SEC-005",
        "category": "security",
        "severity": "warning",
        "pattern": r"\b(pickle|yaml)\.(load|loads)\s*\(",
        "message": "pickle/yaml.load небезопасны для недоверенных данных (RCE).",
        "suggestion": "Используйте yaml.safe_load, json или собственный формат.",
    },
    {
        "id": "SEC-006",
        "category": "security",
        "severity": "warning",
        "pattern": r"\b(hashlib\.)?(md5|sha1)\s*\(",
        "message": "md5/sha1 не подходят для хранения паролей и криптографических подписей.",
        "suggestion": "Используйте bcrypt/argon2 для паролей, sha256+ для подписей.",
    },
    {
        "id": "SEC-007",
        "category": "security",
        "severity": "critical",
        "pattern": r"(?i)\b(dangerouslySetInnerHTML|v-html|innerHTML)\s*=(?![^;\n]*\b(?:esc|escape|escapeHtml|htmlspecialchars|sanitize|sanitizeHtml|renderSafe)\s*\()",
        "message": "Вставка HTML из переменной — потенциальный XSS. Проверьте, что недоверенные данные экранированы (esc()/escapeHtml()/sanitize); подавляется, если экранирование применено в той же строке.",
        "suggestion": "Экранируйте вывод через esc()/escapeHtml() или используйте безопасные шаблоны; не вставляйте недоверенный HTML напрямую.",
    },
    {
        "id": "SEC-008",
        "category": "security",
        "severity": "warning",
        "pattern": r"(?i)\bverify\s*=\s*False",
        "message": "Отключена проверка TLS-сертификата — риск MITM.",
        "suggestion": "Не отключайте verify; для самоподписанных сертификатов добавьте CA в доверенные.",
    },
    {
        "id": "SEC-009",
        "category": "security",
        "severity": "critical",
        "pattern": r"\bexec\.Command\s*\([^)]*[\"']sh[\"']",
        "message": "Запуск через `sh -c` с конкатенацией аргументов — риск command injection.",
        "suggestion": "Передавайте аргументы отдельными элементами без shell.",
    },
    # ---------------------------------------------------------------- performance
    {
        "id": "PERF-001",
        "category": "performance",
        "severity": "warning",
        "pattern": r"\bfor\s+\w+\s+in\s+range\s*\(\s*len\s*\(",
        "message": "Итерация по индексам через range(len(...)) — медленнее и менее читаемо.",
        "suggestion": "Итерируйте напрямую: `for item in items:` или `enumerate(items)`.",
    },
    {
        "id": "PERF-002",
        "category": "performance",
        "severity": "warning",
        "pattern": r"\b\.index\s*\(",
        "message": "list.index() — O(n); в цикле даёт O(n^2).",
        "suggestion": "Используйте dict/set для поиска или enumerate.",
    },
    {
        "id": "PERF-003",
        "category": "performance",
        "severity": "warning",
        "pattern": r"\bwhile\s+True\b",
        "message": "Бесконечный цикл без явного break — риск зависания.",
        "suggestion": "Добавьте условие выхода и лимит итераций.",
    },
    {
        "id": "PERF-004",
        "category": "performance",
        "severity": "nit",
        "pattern": r"\btime\.sleep\s*\(\s*0\s*\)",
        "message": "time.sleep(0) — пустая операция, отладочный артефакт.",
        "suggestion": "Удалите вызов.",
    },
    {
        "id": "PERF-005",
        "category": "performance",
        "severity": "warning",
        "pattern": r"\b\w+\s*\+=\s*[\"']",
        "message": "Конкатенация строк через `+=` в цикле — O(n^2).",
        "suggestion": "Собирайте части в список и склеивайте через ''.join().",
    },
    # ---------------------------------------------------------------- style
    {
        "id": "STYLE-001",
        "category": "style",
        "severity": "nit",
        "pattern": r"[ \t]+$",
        "message": "Хвостовые пробелы в конце строки.",
        "suggestion": "Уберите пробелы в конце строк.",
    },
    {
        "id": "STYLE-002",
        "category": "style",
        "severity": "nit",
        "pattern": r"^\t",
        "message": "Табы вместо пробелов для отступов.",
        "suggestion": "Настройте редактор на 4 пробела (PEP 8).",
    },
    {
        "id": "STYLE-003",
        "category": "style",
        "severity": "nit",
        "pattern": r"^\s*print\s*\(",
        "message": "print() в коде — отладочный вывод.",
        "suggestion": "Замените на логгер или удалите.",
    },
    {
        "id": "STYLE-004",
        "category": "style",
        "severity": "nit",
        "pattern": r"^.{121,}$",
        "message": "Строка длиннее 120 символов.",
        "suggestion": "Разбейте на несколько строк.",
    },
    {
        "id": "STYLE-005",
        "category": "style",
        "severity": "nit",
        "pattern": r"\bvar\s+\w+\s*=",
        "message": "var в JS/TS — функциональная область видимости, источник багов.",
        "suggestion": "Используйте const/let.",
    },
    # ---------------------------------------------------------------- tests
    {
        "id": "TEST-001",
        "category": "tests",
        "severity": "warning",
        "pattern": r"(?i)@pytest\.mark\.(skip|skipif)|@unittest\.skip",
        "message": "Тест пропущен — проверка не выполняется.",
        "suggestion": "Уберите skip или добавьте причину и ссылку на задачу.",
    },
    {
        "id": "TEST-002",
        "category": "tests",
        "severity": "warning",
        "pattern": r"(?i)@pytest\.mark\.(only|xfail)|\.only\s*\(",
        "message": "Тест помечен only/xfail — остальные тесты не запускаются.",
        "suggestion": "Уберите only перед мержем.",
    },
    {
        "id": "TEST-003",
        "category": "tests",
        "severity": "warning",
        "pattern": r"\bassert\s+True\b",
        "message": "assert True — тест всегда проходит, ничего не проверяет.",
        "suggestion": "Напишите реальную проверку результата.",
    },
    {
        "id": "TEST-004",
        "category": "tests",
        "severity": "nit",
        "pattern": r"\btime\.sleep\s*\(",
        "message": "time.sleep в тестах замедляет прогон и делает его недетерминированным.",
        "suggestion": "Используйте моки таймеров или ожидание события.",
    },
    # ---------------------------------------------------------------- edge_cases
    {
        "id": "EDGE-001",
        "category": "edge_cases",
        "severity": "warning",
        "pattern": r"\bint\s*\(",
        "message": "int() без обработки ValueError — упадёт на нечисловом вводе.",
        "suggestion": "Оберните в try/except или валидируйте ввод заранее.",
    },
    {
        "id": "EDGE-002",
        "category": "edge_cases",
        "severity": "warning",
        "pattern": r"\bfloat\s*\(",
        "message": "float() без обработки ValueError — упадёт на нечисловом вводе.",
        "suggestion": "Оберните в try/except или валидируйте ввод заранее.",
    },
    {
        "id": "EDGE-003",
        "category": "edge_cases",
        "severity": "warning",
        "pattern": r"\b\w+\[0\]",
        "message": "Обращение к [0] без проверки пустоты — IndexError.",
        "suggestion": "Проверьте наличие элемента перед индексацией.",
    },
    {
        "id": "EDGE-004",
        "category": "edge_cases",
        "severity": "warning",
        "pattern": r"\b\d+\s*/\s*[a-zA-Z_]\w*",
        "message": "Деление на переменную без проверки нуля — ZeroDivisionError.",
        "suggestion": "Проверяйте делитель на ноль перед делением.",
    },
    {
        "id": "EDGE-005",
        "category": "edge_cases",
        "severity": "warning",
        "pattern": r"\bopen\s*\([^)]*\)(?!\s*as\b)",
        "message": "open() без контекстного менеджера — утечка файлового дескриптора.",
        "suggestion": "Используйте `with open(...) as f:`.",
    },
    {
        "id": "EDGE-006",
        "category": "edge_cases",
        "severity": "nit",
        "pattern": r"\bdatetime\.now\s*\(",
        "message": "datetime.now() возвращает наивное локальное время.",
        "suggestion": "Используйте timezone-aware: datetime.now(timezone.utc).",
    },
    # ---------------------------------------------------------------- a11y
    {
        "id": "A11Y-001",
        "category": "a11y",
        "severity": "warning",
        "pattern": r"<img\b(?![^>]*\balt=)",
        "message": "Картинка без атрибута alt — не доступна скринридерам и теряет смысл при отключённых изображениях.",
        "suggestion": "Добавьте alt с описанием содержимого (декоративные — alt=\"\").",
    },
    {
        "id": "A11Y-002",
        "category": "a11y",
        "severity": "warning",
        "pattern": r"<button\b(?![^>]*\b(aria-label|aria-labelledby))[^>]*>\s*<svg",
        "message": "Кнопка с SVG без aria-label — не имеет доступного имени.",
        "suggestion": "Добавьте aria-label=\"Открыть меню\" или текстовое содержимое.",
    },
    {
        "id": "A11Y-003",
        "category": "a11y",
        "severity": "warning",
        "pattern": r"<(input|select|textarea)\b(?![^>]*\b(aria-label|aria-labelledby))",
        "message": "Поле формы без label/aria-label — скринридер не сообщит, что вводить.",
        "suggestion": "Оберните в <label> или добавьте aria-label/aria-labelledby.",
    },
    {
        "id": "A11Y-004",
        "category": "a11y",
        "severity": "warning",
        "pattern": r"\baria-role\s*=|\baria-labeledby\s*=",
        "message": "Опечатка/невалидный ARIA-атрибут: aria-role (должно быть role) или aria-labeledby (должно быть aria-labelledby).",
        "suggestion": "Исправьте на валидный атрибут WAI-ARIA 1.2.",
    },
    {
        "id": "A11Y-005",
        "category": "a11y",
        "severity": "warning",
        "pattern": r"<(div|span|p)\b[^>]*\bonclick",
        "message": "Клик вешается на неинтерактивный элемент (div/span/p) — недоступно с клавиатуры.",
        "suggestion": "Используйте <button>/<a> или добавьте role + tabindex + обработку Enter/Space.",
    },
    {
        "id": "A11Y-006",
        "category": "a11y",
        "severity": "nit",
        "pattern": r"<html(?![^>]*\blang=)",
        "message": "У <html> нет атрибута lang — скринридеры неверно озвучивают язык.",
        "suggestion": "Добавьте lang=\"ru\" / lang=\"en\".",
    },
    {
        "id": "A11Y-007",
        "category": "a11y",
        "severity": "nit",
        "pattern": r"<h1\b(?![^>]*>).*<h1\b",
        "message": "Более одного <h1> на странице (в пределах diff) — нарушение иерархии.",
        "suggestion": "Оставляйте один h1; подзаголовки — h2–h6.",
    },
    {
        "id": "A11Y-008",
        "category": "a11y",
        "severity": "nit",
        "pattern": r"(?i)\b(?:color|background)\s*:\s*#[0-9a-f]{3,6}\b",
        "message": "Цвет задан raw-hex в коде — вне дизайн-токенов сложно поддерживать контраст.",
        "suggestion": "Вынесите цвет в токены (var(--color-*)) и проверьте контраст >= 4.5:1.",
    },
    {
        "id": "A11Y-009",
        "category": "a11y",
        "severity": "warning",
        "pattern": r"(?i)\b(outline\s*:\s*none|outline\s*:\s*0)",
        "message": "Отключён outline без замены — теряется видимый фокус для клавиатурной навигации.",
        "suggestion": "Замените на :focus-visible стиль: outline 2px solid <акцент>.",
    },
    # ---------------------------------------------------------------- security (depth)
    {
        "id": "SEC-010",
        "category": "security",
        "severity": "critical",
        "pattern": r"(?i)\b(api[_-]?key|secret[_-]?key|access[_-]?token|password|passwd)\s*[:=]\s*[\"'][A-Za-z0-9_\-]{12,}[\"']",
        "message": "Жёстко зашитый секрет/токен/пароль в коде — утечка при публикации репозитория.",
        "suggestion": "Вынесите в переменные окружения / secret-менеджер, никогда не коммитьте.",
    },
    {
        "id": "SEC-011",
        "category": "security",
        "severity": "critical",
        "pattern": r"(?i)\b(SELECT|INSERT|UPDATE|DELETE)\b[^;]*\{\}|\b(sql|query|execute)\s*=\s*[\"'][^\"']*\+",
        "message": "SQL-запрос собирается конкатенацией/интерполяцией — риск SQL-инъекции.",
        "suggestion": "Используйте параметризованные запросы (placeholders) или ORM.",
    },
    {
        "id": "SEC-012",
        "category": "security",
        "severity": "warning",
        "pattern": r"(?i)\b(eval|exec)\s*\(",
        "message": "eval()/exec() исполняет произвольный код — вектор инъекции.",
        "suggestion": "Уберите динамическое исполнение; парсите данные без eval (json, ast.literal_eval).",
    },
    {
        "id": "SEC-013",
        "category": "security",
        "severity": "warning",
        "pattern": r"(?i)shell\s*=\s*True",
        "message": "subprocess с shell=True — команда собирается строкой, риск shell-инъекции.",
        "suggestion": "Передавайте аргументы списком без shell=True.",
    },
    {
        "id": "SEC-014",
        "category": "security",
        "severity": "warning",
        "pattern": r"(?i)\b(pickle\.loads|yaml\.load|yaml\.safe_load\()",
        "message": "Небезопасная десериализация (pickle / yaml.load) может исполнять код при загрузке.",
        "suggestion": "Используйте yaml.safe_load, а pickle — только для доверенных данных.",
    },
]