#!/usr/bin/env python3
"""Generate a current, deterministic quality snapshot for every skill.

This is intentionally a lightweight inventory rather than an LLM judge: it
reports objective signals that can be rerun in CI or before a release.
"""
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
SKILLS = ROOT / "skills"
OUT = ROOT / "docs" / "skill-quality-audit.md"
sys.path.insert(0, str(ROOT / "scripts"))
from validate_skills import parse_frontmatter  # noqa: E402


def main() -> int:
    rows = []
    for directory in sorted(p for p in SKILLS.iterdir() if p.is_dir()):
        path = directory / "SKILL.md"
        text = path.read_text(encoding="utf-8") if path.exists() else ""
        frontmatter, body = parse_frontmatter(text)
        frontmatter = frontmatter or {}
        scripts = list((directory / "scripts").glob("*") if (directory / "scripts").is_dir() else [])
        references = list((directory / "references").glob("*") if (directory / "references").is_dir() else [])
        has_gate = bool(re.search(r"(?i)(exit\s+0|exit\s+1|pass/fail|verification gate|quality gate|output gate|verification)", body))
        has_negative = bool(re.search(r"(?i)(do not use for|do not use|boundaries|не используйте)", body))
        core_sections = sum([
            bool(re.search(r"(?i)(procedure|workflow|pipeline|operating mode|execution protocol|этап|шаг|usage)", body)),
            bool(re.search(r"(?i)(output contract|output format|definition of done|критерии сдачи|report|результат|вывод)", body)),
            has_gate,
            has_negative,
        ])
        eval_path = directory / "evals" / "evals.json"
        eval_count = 0
        if eval_path.exists():
            try:
                import json
                eval_count = len(json.loads(eval_path.read_text(encoding="utf-8")).get("tests", []))
            except (OSError, ValueError, TypeError):
                eval_count = "invalid"
        budget = len(frontmatter.get("description", "")) + len(frontmatter.get("when_to_use", ""))
        rows.append((directory.name, "Y" if frontmatter.get("when_to_use") else "N", budget,
                     len(body.splitlines()), "Y" if scripts else "N", len(references),
                     "{}/4".format(core_sections), "Y" if has_gate else "N", "Y" if has_negative else "N", eval_count))

    lines = [
        "# Skill Quality Audit (objective snapshot)", "",
        f"Generated by `python3 scripts/skill_quality_audit.py`; skills: {len(rows)}.", "",
        "This report deliberately records measurable signals, not an automated claim that a skill is good. "
        "Run `python3 scripts/validate_skills.py --all` for release-blocking structural checks, then inspect "
        "the skill's own output gate and representative examples.", "",
        "| skill | when_to_use | discovery chars | body lines | scripts | references | core sections | output gate wording | negative steer | eval cases |",
        "|---|---:|---:|---:|:---:|---:|---:|:---:|:---:|---:|",
    ]
    for row in rows:
        lines.append("| {} | {} | {} | {} | {} | {} | {} | {} | {} | {} |".format(*row))
    lines += ["", "## Release interpretation", "",
              "- `when_to_use` should be present and discovery chars should stay below the 1,536-character listing budget.",
              "- Keep the instruction body focused; move durable detail into `references/` and repetitive work into `scripts/`.",
              "- A script is not proof by itself: the skill must require running it, report its exit status, and scope failures.",
              "- `negative steer` reduces accidental activation; review it for overlapping skills and deprecated routers.",
              "- `core sections` counts procedure, output contract, verification, and negative steer; it is a review prompt, not a semantic quality proof.",
              "- `eval cases` are objective/manual scenarios; a case is not green until its command or prompt has evidence.",
              "", "## Layer C feedback", "",
              "Usage feedback is captured by `skill-feedback` into `feedback/<skill>/YYYY-MM-DD.jsonl` "
              "and can be fed into the `skill-forge` improvement loop. Re-run this audit after acting on feedback.", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(rows)} skills)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
